/**
 * Copyright (c) 2016-2020, Michael Yang Fuhai (fuhai999@gmail.com).
 * <p>
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.model.base.BaseWechatMenu;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wechat_menu", primaryKey = "id")
public class WechatMenu extends BaseWechatMenu<WechatMenu> {

    private static final Map<String, String> typeStrs = new HashMap<>();

    static {
        typeStrs.put("click", "Trigger keyword");
        typeStrs.put("view", "Link to webpage");
        typeStrs.put("miniprogram", "Jump WeChat Mini Program");
        typeStrs.put("scancode_push", "Scanning incident");
        typeStrs.put("scancode_waitmsg", "Scan the code and push the incident and pop up the \"Message Receive\" prompt box");
        typeStrs.put("pic_sysphoto", "System take pictures");
        typeStrs.put("pic_photo_or_album", "Photo or album to send pictures");
        typeStrs.put("pic_weixin", "WeChat album post map");
        typeStrs.put("location_select", "Geographical selection");
    }


    public String getTypeStr() {
        if (hasChild()) {
            return "A menu";
        }
        String str = typeStrs.get(getType());
        return str != null ? str : "Unknown type";
    }


}
